// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ty2OcOju-gLK9gyeXxCCLlj0cxBav1M',
    appId: '1:271163853097:web:759e3a9f217b4c8eba0f38',
    messagingSenderId: '271163853097',
    projectId: 'my-app-51a14',
    authDomain: 'my-app-51a14.firebaseapp.com',
    storageBucket: 'my-app-51a14.firebasestorage.app',
    measurementId: 'G-QBRSRVN1TF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwwsm8UO5Atfaow_9spjbeHRx-CcepB5I',
    appId: '1:271163853097:android:5701732e94aaa6fbba0f38',
    messagingSenderId: '271163853097',
    projectId: 'my-app-51a14',
    storageBucket: 'my-app-51a14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WWyfuf5JtZyffleVidz0-GBakTuhuDw',
    appId: '1:271163853097:ios:6540e5472d3baa3fba0f38',
    messagingSenderId: '271163853097',
    projectId: 'my-app-51a14',
    storageBucket: 'my-app-51a14.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WWyfuf5JtZyffleVidz0-GBakTuhuDw',
    appId: '1:271163853097:ios:6540e5472d3baa3fba0f38',
    messagingSenderId: '271163853097',
    projectId: 'my-app-51a14',
    storageBucket: 'my-app-51a14.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
